// "use client"

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Sidebar from "@/components/Sidebar";
// import { Provider } from 'react-redux';
// import store from '../store/store';

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="flex min-h-screen">
//           <Provider store={store}>
//             <div className="flex">
//               <Sidebar />
//               <main className="flex-1 p-4">
//                 {children}
//               </main>
//             </div>
//           </Provider>
//           <main className="flex-grow bg-gray-100 p-8">
//             {children}
//           </main>
//         </div>
//       </body>
//     </html>
//   );
// }


"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { Provider } from 'react-redux';
import store from '../store/store';

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <div className="flex min-h-screen">
            <Sidebar />
            <main className="flex-1 p-4">
              {children}
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}

